In [1]:
import numpy as np

def question1(a):
    array = []
    for i in range(a, a+9, 3):
        array.append([i, i+1, i+2])   
    return np.array(array)
        
print(question1(3))
    

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [2]:
def question2(A):
    for i in range(len(A)):
        if A[i] < 0:
            return A
    return A.astype("uint16")

pos_array = np.array([10.2, 3.1, 9.33]) 
neg_array = np.array([10.2, -3.1, 9.33])
question2(neg_array)

array([10.2 , -3.1 ,  9.33])

In [3]:
def question3(a):
    array = np.ones((a, a))
    array[0, :] = np.zeros(a)
    array[-1, :] = np.zeros(a)
    array[:, 0] = np.zeros(a)
    array[:, -1] = np.zeros(a) 
    return array

print(question3(5))

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [4]:
from scipy.interpolate import interp1d

x = np.asarray([1, 5, 10, 20, 30])
y = np.asarray([1, 1.2, 1.8, 3, 10])
f = interp1d(x, y, "quadratic")
print(f(11))

1.8912370689655176
